const myDate = new Date();
console.log(myDate);
// console.log(myDate.getTime());
// console.log('Time in milliseconds from Jan 1,1970 till today',myDate.getTime());
// console.log('Local Year',myDate.getFullYear());
// console.log('Local Month:',myDate.getMonth()+1);
// console.log('Local Date:',myDate.getDate());
// console.log('Local Day:',myDate.getDay());
// console.log('Local Hours:', myDate.getHours());
// console.log('Local Minutes:', myDate.getMinutes());
// console.log('Local Seconds:',myDate.getSeconds());
// console.log('Local MIlliSeconds:',myDate.getMilliseconds());
// console.log(" ");
// console.log('Time Zone Offset:', myDate.getTimezoneOffset()/-60);
// console.log(" ");
// console.log('Get Full Year- UTC:',myDate.getUTCFullYear());
// console.log('UTC-Month:',myDate.getUTCMonth()+1);
// console.log('UTC-Date:',myDate.getUTCDate());
// console.log('UTC-Day:', myDate.getUTCDay());
// console.log('UTC-Hours:', myDate.getUTCHours());
// console.log('UTC-Minutes:', myDate.getUTCMinutes());
// console.log('UTC-Seconds:',myDate.getUTCSeconds());
// console.log('UTC-MIlliSeconds:',myDate.getUTCMilliseconds());
// console.log(" ");
// console.log(myDate.toJSON());
// console.log(myDate.toString());
// console.log(myDate.toUTCString());
// console.log(myDate.toISOString());
// console.log('Date and Time in local format:',myDate.toLocaleString('en-IN', {hour12: true}));
// console.log('Date in local format:', myDate.toLocaleDateString('en-IN'));
// console.log(myDate.toLocaleDateString('en',{dateStyle:"full"}));
// console.log(myDate.toLocaleDateString('en',{dateStyle:"long"}));
// console.log(myDate.toLocaleDateString('en',{dateStyle:"medium"}));
// console.log(myDate.toLocaleDateString('en',{dateStyle:"short"}));
// console.log(myDate.toLocaleTimeString());
// console.log(myDate.toLocaleTimeString('en',{timeStyle:"full"}));
// console.log(myDate.toLocaleTimeString('en',{timeStyle:"long"}));
// console.log(myDate.toLocaleTimeString('en',{timeStyle:"medium"}));
// console.log(myDate.toLocaleTimeString('en',{timeStyle:"short"}));
